[platformio]
default_envs = esp32-s3-supermini

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    esphome/ESPAsyncWebServer-esphome @ ^3.3.0
    esphome/AsyncTCP-esphome @ ^2.1.4
    bblanchon/ArduinoJson @ ^7.3.1
build_flags =
    -D CORE_DEBUG_LEVEL=1

[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = dio
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = huge_app.csv
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_ESP32S3_SUPERMINI=1

[env:esp32-generic]
platform = espressif32
board = esp32dev
board_build.f_cpu = 240000000L
build_flags =
    ${env.build_flags}
    -D BOARD_ESP32_GENERIC=1
